---
- name: nextcloud
  hosts: nextcloudserver
  become: true
  #become_method: sudo

  vars:
    nextcloud_version: 26.0.3
    nextcloud_fqdn: localhost

    nextcloud_os_user: nextclouduser

    mariadb_root_password: p0w3rchin4Main

    nextcloud_db_name: nextcloud
    nextcloud_db_user: nextcloud
    nextcloud_db_password: p0w3rchin4user
    
    nextcloud_admin_user: admin
    nextcloud_admin_password: p0w3rchin4Admin

    install_media: false


  roles:
    - failoverbo.nextcloud
